version: "2"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - "github.com/ikafly144/au_mod_installer"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    unused:
      exported-fields-are-used: true
      generated-is-used: true
      parameters-are-used: true
      local-variables-are-used: true
  exclusions:
    warn-unused: true
    rules:
      - linters:
          - errcheck
        text: "Error return value of `.+\\.Close` is not checked"
