# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: mod-of-us

snapshot:
  version_template: "{{ .Version }}-dev+{{ .Branch }}-{{ .ShortCommit }}"

git:
  tag_sort: -version:creatordate
  prerelease_suffix: "-"

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    - "{{ if not .IsSnapshot }}git diff --exit-code HEAD --{{ end }}"

builds:
  - goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    main: ./client
    ldflags:
      - -s -w -H=windowsgui
    flags:
      - -trimpath
      - -v
    binary: Mod of Us
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - pwsh -NoProfile -File scripts/build_msi.ps1 -Version {{ .Version }} -BuildDirName {{ .ProjectName }}_{{ .Target }}

archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: lib/*.dll
        dst: /
        strip_parent: true
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  extra_files:
    - glob: dist/*.msi
    - glob: dist/*.exe

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]-]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]-]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - '^docs(\([[:word:]-]+\))??!?:.+$'
      - '^test(\([[:word:]-]+\))??!?:.+$'
      - '^ci(\([[:word:]-]+\))??!?:.+$'
      - '^chore(\([[:word:]-]+\))??!?:.+$'
      - '^refactor(\([[:word:]-]+\))??!?:.+$'
      - '^style(\([[:word:]-]+\))??!?:.+$'
      - '^conductor(\([[:word:]-]+\))??!?:.+$'

release:
  replace_existing_draft: true
  prerelease: auto
  make_latest: '{{ eq .Prerelease "" }}'
  github:
    name: au_mod_installer
    owner: ikafly144
  extra_files:
    - glob: dist/*.msi
    - glob: dist/*.exe

announce:
  skip: '{{ or .IsSnapshot ( ne .Prerelease "" ) }}'
  discord:
    enabled: false
    message_template: |-
      {{ .ProjectName }} {{ .Tag }} がリリースされました！
      ダウンロードリンク: <{{ .ReleaseURL }}>
